//
//  UINavigationBar+Private.h
//  Filer
//
//  Created by Jonathan on 07/01/2015.
//  Copyright (c) 2015 Jonathan. All rights reserved.
//


@interface UINavigationBar ()
//    NSMutableArray * _itemStack;
//    double _rightMargin;
//    unsigned int _state;
//    id _delegate;
//    UIView * _backgroundView;
//    UIView * _titleView;
//    NSArray * _leftViews;
//    NSArray * _rightViews;
//    UIView * _prompt;
//    UIView * _accessoryView;
//    UIColor * _barTintColor;
//    id _appearanceStorage;
//    id _currentAlert;
//    ? _navbarFlags;
//    UISwipeGestureRecognizer * _popSwipeGestureRecognizer;
//    UIImageView * _backIndicatorView;
//    NSMutableArray * _slideTransitionClippingViews;
//    _UIViewControllerTransitionContext * _navControllerAnimatingContext;
//    bool _needsUpdateBackIndicatorImage;
//    bool _wantsLetterpressContent;
//    bool __condensed;
//    long long _barPosition;
//    double _requestedMaxBackButtonWidth;
//    NSString * _backdropViewLayerGroupName;
//    NSMutableArray * __animationIds;
+(id)_bottomColorForBackgroundImage:(id)arg2 viewSize:(CGSize)arg3;
+(id)_statusBarBaseTintColorForStyle:(long long)arg2 translucent:(bool)arg3 tintColor:(id)arg4 backgroundImage:(id)arg5 viewSize:(CGSize)arg6;
+(id)_statusBarBaseTintColorForStyle:(long long)arg2 translucent:(bool)arg3 tintColor:(id)arg4;
+(CGSize)defaultSize;
+(void)_initializeForIdiom:(long long)arg2;
+(CGSize)defaultSizeWithPromptForOrientation:(long long)arg2;
+(CGSize)defaultSizeForOrientation:(long long)arg2;
+(bool)_useCustomBackButtonAction;
+(CGSize)defaultSizeWithPrompt;
+(id)defaultPromptFont;
+(void)setDefaultAnimationDuration:(double)arg2;
+(void)_setUseCustomBackButtonAction:(bool)arg2;

-(double)_autolayoutSpacingAtEdge:(int)arg2 inContainer:(id)arg3;
-(double)_autolayoutSpacingAtEdge:(int)arg2 nextToNeighbor:(id)arg3;
-(bool)_hasCustomAutolayoutNeighborSpacing;
-(bool)isElementAccessibilityExposedToInterfaceBuilder;
-(id)_backgroundView;
-(void)_applySPIAppearanceToButtons;
-(void)_setButtonItemTextColor:(id)arg2 shadowColor:(id)arg3 forState:(unsigned long long)arg4;
-(void)_setBackgroundView:(id)arg2;
-(double)_shadowAlpha;
-(void)_setShadowAlpha:(double)arg2;
-(void)_setBackgroundImage:(id)arg2 mini:(id)arg3;
-(void)_setButtonBackgroundImage:(id)arg2 mini:(id)arg3 forStates:(unsigned long long)arg4;
-(void)_setBackButtonBackgroundImage:(id)arg2 mini:(id)arg3 forStates:(unsigned long long)arg4;
-(void)_setButtonItemTextColor:(id)arg2 shadowColor:(id)arg3;
-(void)_setPressedButtonItemTextColor:(id)arg2 shadowColor:(id)arg3;
-(void)_setButtonTextShadowOffset:(CGSize)arg2;
-(void)_setReversesButtonTextShadowOffsetWhenPressed:(bool)arg2;
-(id)_backgroundViewForPalette:(id)arg2;
-(void)_palette:(id)arg2 isAttaching:(bool)arg3 didComplete:(bool)arg4;
-(id)initWithFrame:(CGRect)arg2;
-(void)setAutoresizingMask:(unsigned long long)arg2;
-(void)dealloc;
-(void)drawRect:(CGRect)arg2;
-(id)initWithCoder:(id)arg2;
-(void)_populateArchivedSubviews:(id)arg2;
-(void)encodeWithCoder:(id)arg2;
-(id)hitTest:(CGPoint)arg2 withEvent:(id)arg3;
-(void)setNeedsLayout;
-(void)setHidden:(bool)arg2;
-(void)setFrame:(CGRect)arg2;
-(void)layoutSubviews;
-(void)setBounds:(CGRect)arg2;
-(bool)_contentHuggingDefault_isUsuallyFixedHeight;
-(CGSize)sizeThatFits:(CGSize)arg2;
-(id)_basicAnimationForView:(id)arg2 withKeyPath:(id)arg3;
-(id)_timingFunctionForAnimationInView:(id)arg2 withKeyPath:(id)arg3;
-(int)state;
-(bool)gestureRecognizerShouldBegin:(id)arg2;
-(bool)_hasBackButton;
-(void)_setVisualAltitude:(double)arg2;
-(void)_setVisualAltitudeBias:(CGSize)arg2;
-(id)_statusBarTintColor;
-(bool)isTranslucent;
-(void)touchesCancelled:(id)arg2 withEvent:(id)arg3;
-(bool)isLocked;
-(bool)_canHandleStatusBarTouchAtLocation:(CGPoint)arg2;
-(void)touchesBegan:(id)arg2 withEvent:(id)arg3;
-(void)touchesMoved:(id)arg2 withEvent:(id)arg3;
-(void)touchesEnded:(id)arg2 withEvent:(id)arg3;
-(void)setCenter:(CGPoint)arg2;
-(void)setTranslatesAutoresizingMaskIntoConstraints:(bool)arg2;
-(bool)_canDrawContent;
-(void)invalidateIntrinsicContentSize;
-(void)tintColorDidChange;
-(void)_willMoveToWindow:(id)arg2;
-(void)_didMoveFromWindow:(id)arg2 toWindow:(id)arg3;
-(void)didAddSubview:(id)arg2;
-(void)willRemoveSubview:(id)arg2;
-(void)disableAnimation;
-(void)enableAnimation;
-(id)hitTest:(CGPoint)arg2 forEvent:(id)arg3;
-(CGSize)intrinsicContentSize;
-(void)_didChangeFromIdiom:(long long)arg2 onScreen:(id)arg3 traverseHierarchy:(bool)arg4;
-(bool)_subclassImplementsDrawRect;
-(bool)_deferShadowToSearchBar;
-(id)_appearanceStorage;
-(void)_updateTitleView;
-(void)updatePrompt;
-(void)_setLeftViews:(id)arg2 rightViews:(id)arg3;
-(void)showBackButton:(bool)arg2 animated:(bool)arg3;
-(bool)isMinibar;
-(void)setTitleView:(id)arg2;
-(id)prompt;
-(void)setPrompt:(id)arg2;
-(id)_shadowView;
-(long long)_currentBarStyle;
-(void)_updateNavigationBarItemsForStyle:(long long)arg2;
-(void)_setNeedsUpdateBackIndicatorImage:(bool)arg2;
-(void)_updateBackIndicatorImage;
-(void)_updateBackgroundColor;
-(id)_effectiveBarTintColor;
-(void)_effectiveBarTintColorDidChangeWithPreviousColor:(id)arg2;
-(void)_propagateEffectiveBarTintColorWithPreviousColor:(id)arg2;
-(void)_tintViewAppearanceDidChange;
-(void)_updatePaletteBackgroundIfNecessary;
-(void)_updateBackgroundImage;
-(long long)_activeBarMetrics;
-(id)currentBackButton;
-(long long)_defaultBarMetrics;
-(CGSize)defaultSizeForOrientation:(long long)arg2;
-(void)drawBackgroundInRect:(CGRect)arg2 withStyle:(long long)arg3;
-(void)_setDefaultBarMetrics:(long long)arg2;
-(void)_setActiveBarMetrics:(long long)arg2;
-(void)_setBackIndicatorLeftMargin:(double)arg2;
-(bool)_subclassImplementsDrawBackgroundInRect;
-(void)_handlePopSwipe:(id)arg2;
-(void)_accessibilityButtonShapesDidChangeNotification:(id)arg2;
-(void)_updateOpacity;
-(void)_commonNavBarInit;
-(void)_setupTopNavItem:(id)arg2 oldTopNavItem:(id)arg3;
-(void)_reenableUserInteraction;
-(id)_defaultTitleFontWithScaleAdjustment:(double)arg2;
-(id)_defaultTitleFontFittingHeight:(double)arg2 withScaleAdjustment:(double)arg3;
-(void)_fadeViewOut:(id)arg2;
-(void)_pushNavigationItem:(id)arg2 transition:(int)arg3;
-(void)_setAnimationIds:(id)arg2;
-(id)_effectiveDelegate;
-(void)_startInteractiveNavigationBarTransition;
-(void)pushNavigationItem:(id)arg2;
-(bool)_wantsLetterpressContent;
-(id)_animationIds;
-(void)_updateInteractiveStatusBarTransitionPercent:(double)arg2 isFinished:(bool)arg3 didComplete:(bool)arg4 completionSpeed:(double)arg5 completionCurve:(long long)arg6;
-(long long)_barStyle:(bool)arg2;
-(bool)titleAutoresizesToFit;
-(void)setTitleAutoresizesToFit:(bool)arg2;
-(bool)_hasInvisibleCustomBackgroundImage;
-(bool)_barTranslucenceSuppressesAdaptiveBackdrop;
-(bool)_barStyleSuppressesAdaptiveBackdrop;
-(bool)_customBackgroundImageSuppressesAdaptiveBackdropForPalette;
-(bool)_backgroundViewSuppressesAdaptiveBackdrop;
-(bool)_customBackgroundImageSuppressesAdaptiveBackdrop;
-(bool)_wantsAdaptiveBackdropWhenNotHidden;
-(bool)isAnimationEnabled;
-(void)_prepareForPushAnimationWithItems:(id)arg2;
-(void)_setBarStyle:(long long)arg2;
-(void)_resetBackgroundImageAsNecessary;
-(void)_startPushAnimationFromItems:(id)arg2 fromBarStyle:(long long)arg3;
-(void)_startBarStyleAnimation:(long long)arg2 withTintColor:(id)arg3;
-(void)_crossFadeToBarBackgroundImageForItem:(id)arg2;
-(id)_popNavigationItemWithTransition:(int)arg2;
-(void)popNavigationItem;
-(void)_prepareForPopAnimationWithNewTopItem:(id)arg2;
-(id)navigationItems;
-(void)_startPopAnimationFromItems:(id)arg2 fromBarStyle:(long long)arg3 toItems:(id)arg4 toBarStyle:(long long)arg5;
-(int)_transitionForOldItems:(id)arg2 newItems:(id)arg3;
-(void)_setItems:(id)arg2 transition:(int)arg3;
-(bool)_didVisibleItemsChangeWithNewItems:(id)arg2 oldItems:(id)arg3;
-(void)_removeItemsFromSuperview:(id)arg2;
-(void)_setItems:(id)arg2 transition:(int)arg3 reset:(bool)arg4;
-(void)setLocked:(bool)arg2;
-(void)_addItem:(id)arg2 withEffectiveDelegate:(id)arg3 transition:(int)arg4;
-(bool)forceFullHeightInLandscape;
-(long long)effectiveInterfaceOrientation;
-(id)_nthNavigationItemFromTop:(long long)arg2;
-(unsigned long long)_subviewIndexAboveBackground;
-(void)_cancelInteractiveTransition;
-(void)_decrementAnimationCountIfNecessary;
-(id)navigationItemAtPoint:(CGPoint)arg2;
-(id)_commonHitTest:(CGPoint)arg2 forView:(id)arg3;
-(void)_setBackIndicatorPressed:(bool)arg2 initialPress:(bool)arg3;
-(id)_currentBackButtonForNthItemFromTop:(unsigned long long)arg2;
-(id)backButtonViewAtPoint:(CGPoint)arg2;
-(bool)_shouldPopForTouchAtPoint:(CGPoint)arg2;
-(void)_popForTouchAtPoint:(CGPoint)arg2;
-(void)_handleMouseDownAtPoint:(CGPoint)arg2;
-(void)_handleMouseUpAtPoint:(CGPoint)arg2;
-(void)_setBarPosition:(long long)arg2;
-(void)_configurePaletteConstraintsIfNecessary;
-(bool)_needsUpdateBackIndicatorImage;
-(void)addConstraint:(id)arg2;
-(void)removeConstraint:(id)arg2;
-(void)_updateNavigationBarItem:(id)arg2 forStyle:(long long)arg3 previousTintColor:(id)arg4;
-(void)_updateNavigationBarItem:(id)arg2 forStyle:(long long)arg3;
-(void)_customViewChangedForButtonItem:(id)arg2;
-(id)_currentLeftViews;
-(id)_currentRightViews;
-(void)_updateNavigationBarItemsForStyle:(long long)arg2 previousTintColor:(id)arg3;
-(bool)_wantsAdaptiveBackdrop;
-(void)setTranslucent:(bool)arg2;
-(bool)_legacyIsTranslucent;
-(bool)_modernIsTranslucent;
-(void)_setIsContainedInPopover:(bool)arg2;
-(bool)_shouldShowBackButtonForNavigationItem:(id)arg2;
-(void)_fadeViewsIn:(id)arg2;
-(CGRect)promptBounds;
-(void)showButtonsWithLeft:(id)arg2 right:(id)arg3 leftBack:(bool)arg4;
-(void)showLeftButton:(id)arg2 withStyle:(int)arg3 rightButton:(id)arg4 withStyle:(int)arg5;
-(id)createButtonWithContents:(id)arg2 width:(double)arg3 barStyle:(long long)arg4 buttonStyle:(int)arg5 isRight:(bool)arg6;
-(void)_setLeftView:(id)arg2 rightView:(id)arg3;
-(bool)_isIncomingButtonSameAsOutgoingButtonOnLeft:(bool)arg2;
-(void)_getTitleViewFrame:(CGRect *)arg2 leftViewFrames:(id)arg3 rightViewFrames:(id)arg4;
-(void)_incrementAnimationCountIfNecessary;
-(void)_fadeViewsOut:(id)arg2;
-(void)_showLeftRightButtonsAnimationDidStop:(id)arg2 finished:(id)arg3 context:(id)arg4;
-(void)_hideButtonsAnimationDidStop:(id)arg2 finished:(id)arg3 context:(id)arg4;
-(id)currentLeftView;
-(void)showHideBackButtomAnimationDidStop:(id)arg2 finished:(id)arg3 context:(id)arg4;
-(void)_accessibilityButtonShapesParametersDidChange;
-(bool)_suppressBackIndicator;
-(id)_effectiveBackIndicatorImage;
-(void)_layoutBackgroundViewConsideringAdaptiveBackdropAndChangedHeight:(bool)arg2;
-(void)_barSizeDidChangeAndSoDidHeight:(bool)arg2;
-(double)topItemAlpha;
-(void)_getTitleViewFrame:(CGRect *)arg2 leftViewFrames:(id)arg3 rightViewFrames:(id)arg4 forItemAtIndex:(unsigned long long)arg5;
-(void)_backgroundFadeDidFinish:(id)arg2 finished:(id)arg3 context:(id)arg4;
-(id)_effectiveBackIndicatorTransitionMaskImage;
-(double)_backIndicatorClippingMargin;
-(void)_wrapView:(id)arg2 inClippingViewWithLeftBoundary:(double)arg3 rightBoundary:(double)arg4 leftMaskImage:(id)arg5 leftMaskIsChevron:(bool)arg6 rightMaskImage:(id)arg7;
-(double)_backTitleWidthOverTitleWidthForMatchingBackButtonView:(id)arg2 titleView:(id)arg3 withBackButtonWidth:(double)arg4;
-(void)_navigationAnimationDidFinish:(id)arg2 finished:(id)arg3 context:(id)arg4;
-(id)_allViews;
-(double)defaultBackButtonAlignmentHeight;
-(void)_getTitleViewFrame:(CGRect *)arg2 leftViewFrames:(id)arg3 rightViewFrames:(id)arg4 forItemAtIndex:(unsigned long long)arg5 returnedIdealWidthOfTextContent:(double *)arg6 availableLayoutWidthForTextContent:(double *)arg7 idealBackButtonWidth:(double *)arg8;
-(double)_effectiveBackIndicatorLeftMargin;
-(long long)_barPosition;
-(long long)barPosition;
-(long long)_barTranslucence;
-(void)_setCondensed:(bool)arg2;
-(double)_heightIncludingBackground;
-(void)_setBackdropViewLayerGroupName:(id)arg2;
-(void)_setWantsLetterpressContent:(bool)arg2;
-(void)_setBackIndicatorImage:(id)arg2;
-(id)_backIndicatorImage;
-(double)_backIndicatorLeftMargin;
-(long long)_itemStackCount;
-(bool)_hidesShadow;
-(void)_setHidesShadow:(bool)arg2;
-(void)_setDeferShadowToSearchBar:(bool)arg2;
-(id)_defaultTitleFont;
-(void)setAccessoryView:(id)arg2 animate:(bool)arg3;
-(void)_updateInteractiveTransition:(double)arg2;
-(void)_finishInteractiveTransition:(double)arg2 completionSpeed:(double)arg3 completionCurve:(long long)arg4;
-(void)_cancelInteractiveTransition:(double)arg2 completionSpeed:(double)arg3 completionCurve:(long long)arg4;
-(bool)_wantsAdaptiveBackdropForPalette;
-(void)_popNestedNavigationItem;
-(void)_pushNestedNavigationItem:(id)arg2;
-(void)_setItemsUpToItem:(id)arg2 transition:(id)arg3;
-(void)_addItems:(id)arg2 withEffectiveDelegate:(id)arg3 transition:(int)arg4;
-(void)setNavigationItems:(id)arg2;
-(void)_cancelInProgressPushOrPop;
-(void)_reenableUserInteractionWhenReadyWithContext:(id)arg2;
-(void)_evaluateBackIndicatorForHilightedState:(bool)arg2 ofBarButtonItem:(id)arg3 inNavigationItem:(id)arg4;
-(long long)_statusBarStyle;
-(void)setForceFullHeightInLandscape:(bool)arg2;
-(id)buttonItemShadowColor;
-(id)buttonItemTextColor;
-(id)_titleTextColor;
-(void)setRightMargin:(double)arg2;
-(id)currentRightView;
-(id)promptView;
-(unsigned int)animationDisabledCount;
-(void)drawBackButtonBackgroundInRect:(CGRect)arg2 withStyle:(long long)arg3 pressed:(bool)arg4;
-(void)showButtonsWithLeftTitle:(id)arg2 rightTitle:(id)arg3;
-(void)showButtonsWithLeftTitle:(id)arg2 rightTitle:(id)arg3 leftBack:(bool)arg4;
-(void)setButton:(int)arg2 enabled:(bool)arg3;
-(void)hideButtons;
-(CGRect)availableTitleArea;
-(void)setTopItemAlpha:(double)arg2;
-(void)_removeAccessoryView;
-(CGRect)_boundsForPrompt:(id)arg2 inRect:(CGRect)arg3 withFont:(id)arg4 barStyle:(long long)arg5;
-(void)_animateOldBackButtonView:(id)arg2 toNewBackButtonView:(id)arg3 duration:(double)arg4 initialFrameForIncomingView:(id)arg5 destinationFrameForOutgoingView:(id)arg6 animationCleanup:(id)arg7;
-(void)_fadeAllViewsOut;
-(void)_fadeAllViewsIn;
-(id)_itemStack;
-(void)_navBarButtonPressed:(id)arg2;
-(void)_setAutoAdjustTitle:(bool)arg2;
-(bool)_gestureRecognizerShouldBegin:(id)arg2;
-(long long)_backgroundBackdropStyle;
-(double)_requestedMaxBackButtonWidth;
-(void)_setRequestedMaxBackButtonWidth:(double)arg2;
-(id)_backdropViewLayerGroupName;
-(bool)_isCondensed;

@end
